"""empty message

Revision ID: b2484b7e91b7
Revises: 182a6d04d355
Create Date: 2019-11-18 19:23:19.620795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2484b7e91b7'
down_revision = '182a6d04d355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'created_date')
    # ### end Alembic commands ###
